hoistPattern:
  - '*'
hoistedDependencies: {}
included:
  dependencies: true
  devDependencies: true
  optionalDependencies: true
injectedDeps: {}
layoutVersion: 5
nodeLinker: isolated
packageManager: pnpm@10.15.1
pendingBuilds: []
prunedAt: Thu, 25 Sep 2025 01:06:36 GMT
publicHoistPattern: []
registries:
  '@jsr': https://npm.jsr.io/
  default: https://registry.npmjs.org/
skipped: []
storeDir: C:\Users\Administrator\AppData\Local\pnpm\store\v10
virtualStoreDir: C:\fusheng\star\node_modules\.pnpm
virtualStoreDirMaxLength: 60
